export const companies = [
  {
    id: "google",
    name: "Google",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg",
    description: "Focuses on Graphs, DP, Trees, and obscure algorithms.",
    questions: [
      { id: 1, title: "Two Sum", difficulty: "Easy", link: "https://leetcode.com/problems/two-sum/" },
      { id: 2, title: "Median of Two Sorted Arrays", difficulty: "Hard", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
      { id: 3, title: "Longest Valid Parentheses", difficulty: "Hard", link: "https://leetcode.com/problems/longest-valid-parentheses/" },
      { id: 4, title: "Merge k Sorted Lists", difficulty: "Hard", link: "https://leetcode.com/problems/merge-k-sorted-lists/" },
      { id: 5, title: "Trapping Rain Water", difficulty: "Hard", link: "https://leetcode.com/problems/trapping-rain-water/" },
      { id: 6, title: "Edit Distance", difficulty: "Hard", link: "https://leetcode.com/problems/edit-distance/" },
      { id: 7, title: "Maximal Rectangle", difficulty: "Hard", link: "https://leetcode.com/problems/maximal-rectangle/" },
      { id: 8, title: "Word Ladder II", difficulty: "Hard", link: "https://leetcode.com/problems/word-ladder-ii/" },
      { id: 9, title: "The Skyline Problem", difficulty: "Hard", link: "https://leetcode.com/problems/the-skyline-problem/" },
      { id: 10, title: "Sliding Window Maximum", difficulty: "Hard", link: "https://leetcode.com/problems/sliding-window-maximum/" },
      { id: 11, title: "Logger Rate Limiter", difficulty: "Easy", link: "https://leetcode.com/problems/logger-rate-limiter/" },
      { id: 12, title: "Design Search Autocomplete System", difficulty: "Hard", link: "https://leetcode.com/problems/design-search-autocomplete-system/" },
      { id: 13, title: "Find First and Last Position of Element in Sorted Array", difficulty: "Medium", link: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/" },
      { id: 14, title: "Container With Most Water", difficulty: "Medium", link: "https://leetcode.com/problems/container-with-most-water/" },
      { id: 15, title: "3Sum", difficulty: "Medium", link: "https://leetcode.com/problems/3sum/" },
      { id: 16, title: "Next Permutation", difficulty: "Medium", link: "https://leetcode.com/problems/next-permutation/" },
      { id: 17, title: "Multiply Strings", difficulty: "Medium", link: "https://leetcode.com/problems/multiply-strings/" },
      { id: 18, title: "Jump Game II", difficulty: "Medium", link: "https://leetcode.com/problems/jump-game-ii/" },
      { id: 19, title: "Rotate Image", difficulty: "Medium", link: "https://leetcode.com/problems/rotate-image/" },
      { id: 20, title: "Group Anagrams", difficulty: "Medium", link: "https://leetcode.com/problems/group-anagrams/" },
      { id: 21, title: "Merge Intervals", difficulty: "Medium", link: "https://leetcode.com/problems/merge-intervals/" },
      { id: 22, title: "Insert Interval", difficulty: "Medium", link: "https://leetcode.com/problems/insert-interval/" },
      { id: 23, title: "Unique Paths", difficulty: "Medium", link: "https://leetcode.com/problems/unique-paths/" },
      { id: 24, title: "Minimum Path Sum", difficulty: "Medium", link: "https://leetcode.com/problems/minimum-path-sum/" },
      { id: 25, title: "Valid Number", difficulty: "Hard", link: "https://leetcode.com/problems/valid-number/" },
      { id: 26, title: "Text Justification", difficulty: "Hard", link: "https://leetcode.com/problems/text-justification/" },
      { id: 27, title: "Simplify Path", difficulty: "Medium", link: "https://leetcode.com/problems/simplify-path/" },
      { id: 28, title: "Minimum Window Substring", difficulty: "Hard", link: "https://leetcode.com/problems/minimum-window-substring/" },
      { id: 29, title: "Largest Rectangle in Histogram", difficulty: "Hard", link: "https://leetcode.com/problems/largest-rectangle-in-histogram/" },
      { id: 30, title: "Validate Binary Search Tree", difficulty: "Medium", link: "https://leetcode.com/problems/validate-binary-search-tree/" },
      { id: 31, title: "Construct Binary Tree from Preorder and Inorder Traversal", difficulty: "Medium", link: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/" },
      { id: 32, title: "Best Time to Buy and Sell Stock III", difficulty: "Hard", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/" },
      { id: 33, title: "Binary Tree Maximum Path Sum", difficulty: "Hard", link: "https://leetcode.com/problems/binary-tree-maximum-path-sum/" },
      { id: 34, title: "Longest Consecutive Sequence", difficulty: "Medium", link: "https://leetcode.com/problems/longest-consecutive-sequence/" },
      { id: 35, title: "Word Break II", difficulty: "Hard", link: "https://leetcode.com/problems/word-break-ii/" },
      { id: 36, title: "LRU Cache", difficulty: "Medium", link: "https://leetcode.com/problems/lru-cache/" },
      { id: 37, title: "Course Schedule", difficulty: "Medium", link: "https://leetcode.com/problems/course-schedule/" },
      { id: 38, title: "Course Schedule II", difficulty: "Medium", link: "https://leetcode.com/problems/course-schedule-ii/" },
      { id: 39, title: "Number of Islands", difficulty: "Medium", link: "https://leetcode.com/problems/number-of-islands/" },
      { id: 40, title: "Skyline Problem", difficulty: "Hard", link: "https://leetcode.com/problems/the-skyline-problem/" },
      { id: 41, title: "Count of Smaller Numbers After Self", difficulty: "Hard", link: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/" },
      { id: 42, title: "Remove Invalid Parentheses", difficulty: "Hard", link: "https://leetcode.com/problems/remove-invalid-parentheses/" },
      { id: 43, title: "Longest Increasing Path in a Matrix", difficulty: "Hard", link: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/" },
      { id: 44, title: "Count of Range Sum", difficulty: "Hard", link: "https://leetcode.com/problems/count-of-range-sum/" },
      { id: 45, title: "Android Unlock Patterns", difficulty: "Medium", link: "https://leetcode.com/problems/android-unlock-patterns/" },
      { id: 46, title: "Logger Rate Limiter", difficulty: "Easy", link: "https://leetcode.com/problems/logger-rate-limiter/" },
      { id: 47, title: "Sort Transformed Array", difficulty: "Medium", link: "https://leetcode.com/problems/sort-transformed-array/" },
      { id: 48, title: "Design Snake Game", difficulty: "Medium", link: "https://leetcode.com/problems/design-snake-game/" },
      { id: 49, title: "Russian Doll Envelopes", difficulty: "Hard", link: "https://leetcode.com/problems/russian-doll-envelopes/" },
      { id: 50, title: "Split Array Largest Sum", difficulty: "Hard", link: "https://leetcode.com/problems/split-array-largest-sum/" }
    ]
  },
  {
    id: "amazon",
    name: "Amazon",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
    description: "Heavy on Arrays, Strings, HashMaps, and 'Top K' elements.",
    questions: [
      { id: 1, title: "Two Sum", difficulty: "Easy", link: "https://leetcode.com/problems/two-sum/" },
      { id: 2, title: "Longest Substring Without Repeating Characters", difficulty: "Medium", link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
      { id: 3, title: "String to Integer (atoi)", difficulty: "Medium", link: "https://leetcode.com/problems/string-to-integer-atoi/" },
      { id: 4, title: "Container With Most Water", difficulty: "Medium", link: "https://leetcode.com/problems/container-with-most-water/" },
      { id: 5, title: "Integer to Roman", difficulty: "Medium", link: "https://leetcode.com/problems/integer-to-roman/" },
      { id: 6, title: "3Sum", difficulty: "Medium", link: "https://leetcode.com/problems/3sum/" },
      { id: 7, title: "Group Anagrams", difficulty: "Medium", link: "https://leetcode.com/problems/group-anagrams/" },
      { id: 8, title: "Maximum Subarray", difficulty: "Medium", link: "https://leetcode.com/problems/maximum-subarray/" },
      { id: 9, title: "Merge Intervals", difficulty: "Medium", link: "https://leetcode.com/problems/merge-intervals/" },
      { id: 10, title: "Word Search", difficulty: "Medium", link: "https://leetcode.com/problems/word-search/" },
      { id: 11, title: "Reorder Data in Log Files", difficulty: "Medium", link: "https://leetcode.com/problems/reorder-data-in-log-files/" },
      { id: 12, title: "Meeting Rooms II", difficulty: "Medium", link: "https://leetcode.com/problems/meeting-rooms-ii/" },
      { id: 13, title: "Top K Frequent Elements", difficulty: "Medium", link: "https://leetcode.com/problems/top-k-frequent-elements/" },
      { id: 14, title: "Top K Frequent Words", difficulty: "Medium", link: "https://leetcode.com/problems/top-k-frequent-words/" },
      { id: 15, title: "K Closest Points to Origin", difficulty: "Medium", link: "https://leetcode.com/problems/k-closest-points-to-origin/" },
      { id: 16, title: "Product of Array Except Self", difficulty: "Medium", link: "https://leetcode.com/problems/product-of-array-except-self/" },
      { id: 17, title: "Valid Parentheses", difficulty: "Easy", link: "https://leetcode.com/problems/valid-parentheses/" },
      { id: 18, title: "Merge Two Sorted Lists", difficulty: "Easy", link: "https://leetcode.com/problems/merge-two-sorted-lists/" },
      { id: 19, title: "LRU Cache", difficulty: "Medium", link: "https://leetcode.com/problems/lru-cache/" },
      { id: 20, title: "Trapping Rain Water", difficulty: "Hard", link: "https://leetcode.com/problems/trapping-rain-water/" },
      { id: 21, title: "Rotting Oranges", difficulty: "Medium", link: "https://leetcode.com/problems/rotting-oranges/" },
      { id: 22, title: "Search in Rotated Sorted Array", difficulty: "Medium", link: "https://leetcode.com/problems/search-in-rotated-sorted-array/" },
      { id: 23, title: "Copy List with Random Pointer", difficulty: "Medium", link: "https://leetcode.com/problems/copy-list-with-random-pointer/" },
      { id: 24, title: "Design Tic-Tac-Toe", difficulty: "Medium", link: "https://leetcode.com/problems/design-tic-tac-toe/" },
      { id: 25, title: "Design Search Autocomplete System", difficulty: "Hard", link: "https://leetcode.com/problems/design-search-autocomplete-system/" },
      { id: 26, title: "Median of Two Sorted Arrays", difficulty: "Hard", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
      { id: 27, title: "Alien Dictionary", difficulty: "Hard", link: "https://leetcode.com/problems/alien-dictionary/" },
      { id: 28, title: "Course Schedule", difficulty: "Medium", link: "https://leetcode.com/problems/course-schedule/" },
      { id: 29, title: "Word Ladder", difficulty: "Hard", link: "https://leetcode.com/problems/word-ladder/" },
      { id: 30, title: "Word Ladder II", difficulty: "Hard", link: "https://leetcode.com/problems/word-ladder-ii/" },
      { id: 31, title: "Critical Connections in a Network", difficulty: "Hard", link: "https://leetcode.com/problems/critical-connections-in-a-network/" },
      { id: 32, title: "Concatenated Words", difficulty: "Hard", link: "https://leetcode.com/problems/concatenated-words/" },
      { id: 33, title: "Boundary of Binary Tree", difficulty: "Medium", link: "https://leetcode.com/problems/boundary-of-binary-tree/" },
      { id: 34, title: "Prison Cells After N Days", difficulty: "Medium", link: "https://leetcode.com/problems/prison-cells-after-n-days/" },
      { id: 35, title: "Partition Labels", difficulty: "Medium", link: "https://leetcode.com/problems/partition-labels/" },
      { id: 36, title: "Most Common Word", difficulty: "Easy", link: "https://leetcode.com/problems/most-common-word/" },
      { id: 37, title: "Kth Largest Element in an Array", difficulty: "Medium", link: "https://leetcode.com/problems/kth-largest-element-in-an-array/" },
      { id: 38, title: "Sliding Window Maximum", difficulty: "Hard", link: "https://leetcode.com/problems/sliding-window-maximum/" },
      { id: 39, title: "Find Median from Data Stream", difficulty: "Hard", link: "https://leetcode.com/problems/find-median-from-data-stream/" },
      { id: 40, title: "Serialize and Deserialize Binary Tree", difficulty: "Hard", link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/" },
      { id: 41, title: "Diameter of Binary Tree", difficulty: "Easy", link: "https://leetcode.com/problems/diameter-of-binary-tree/" },
      { id: 42, title: "Subtree of Another Tree", difficulty: "Easy", link: "https://leetcode.com/problems/subtree-of-another-tree/" },
      { id: 43, title: "Symmetric Tree", difficulty: "Easy", link: "https://leetcode.com/problems/symmetric-tree/" },
      { id: 44, title: "Binary Tree Zigzag Level Order Traversal", difficulty: "Medium", link: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/" },
      { id: 45, title: "Lowest Common Ancestor of a Binary Tree", difficulty: "Medium", link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/" },
      { id: 46, title: "Word Search II", difficulty: "Hard", link: "https://leetcode.com/problems/word-search-ii/" },
      { id: 47, title: "Longest Palindromic Substring", difficulty: "Medium", link: "https://leetcode.com/problems/longest-palindromic-substring/" },
      { id: 48, title: "Search a 2D Matrix II", difficulty: "Medium", link: "https://leetcode.com/problems/search-a-2d-matrix-ii/" },
      { id: 49, title: "Meeting Rooms", difficulty: "Easy", link: "https://leetcode.com/problems/meeting-rooms/" },
      { id: 50, title: "Count Primes", difficulty: "Medium", link: "https://leetcode.com/problems/count-primes/" }
    ]
  },
  {
    id: "meta",
    name: "Meta",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Meta-Logo.png",
    description: "Speed is key. Arrays, Strings, and Graphs. Known for asking questions exactly from LeetCode.",
    questions: [
      { id: 1, title: "Regular Expression Matching", difficulty: "Hard", link: "https://leetcode.com/problems/regular-expression-matching/" },
      { id: 2, title: "Letter Combinations of a Phone Number", difficulty: "Medium", link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/" },
      { id: 3, title: "Remove Nth Node From End of List", difficulty: "Medium", link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
      { id: 4, title: "Divide Two Integers", difficulty: "Medium", link: "https://leetcode.com/problems/divide-two-integers/" },
      { id: 5, title: "Next Permutation", difficulty: "Medium", link: "https://leetcode.com/problems/next-permutation/" },
      { id: 6, title: "Search in Rotated Sorted Array", difficulty: "Medium", link: "https://leetcode.com/problems/search-in-rotated-sorted-array/" },
      { id: 7, title: "Multiply Strings", difficulty: "Medium", link: "https://leetcode.com/problems/multiply-strings/" },
      { id: 8, title: "Permutations", difficulty: "Medium", link: "https://leetcode.com/problems/permutations/" },
      { id: 9, title: "Pow(x, n)", difficulty: "Medium", link: "https://leetcode.com/problems/powx-n/" },
      { id: 10, title: "N-Queens", difficulty: "Hard", link: "https://leetcode.com/problems/n-queens/" },
      { id: 11, title: "Verifying an Alien Dictionary", difficulty: "Easy", link: "https://leetcode.com/problems/verifying-an-alien-dictionary/" },
      { id: 12, title: "Minimum Remove to Make Valid Parentheses", difficulty: "Medium", link: "https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses/" },
      { id: 13, title: "Valid Palindrome II", difficulty: "Easy", link: "https://leetcode.com/problems/valid-palindrome-ii/" },
      { id: 14, title: "Product of Array Except Self", difficulty: "Medium", link: "https://leetcode.com/problems/product-of-array-except-self/" },
      { id: 15, title: "Subarray Sum Equals K", difficulty: "Medium", link: "https://leetcode.com/problems/subarray-sum-equals-k/" },
      { id: 16, title: "Add Strings", difficulty: "Easy", link: "https://leetcode.com/problems/add-strings/" },
      { id: 17, title: "Merge Sorted Array", difficulty: "Easy", link: "https://leetcode.com/problems/merge-sorted-array/" },
      { id: 18, title: "Find First and Last Position of Element in Sorted Array", difficulty: "Medium", link: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/" },
      { id: 19, title: "Kth Largest Element in an Array", difficulty: "Medium", link: "https://leetcode.com/problems/kth-largest-element-in-an-array/" },
      { id: 20, title: "Binary Tree Right Side View", difficulty: "Medium", link: "https://leetcode.com/problems/binary-tree-right-side-view/" },
      { id: 21, title: "Interval List Intersections", difficulty: "Medium", link: "https://leetcode.com/problems/interval-list-intersections/" },
      { id: 22, title: "Vertical Order Traversal of a Binary Tree", difficulty: "Hard", link: "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/" },
      { id: 23, title: "Simplify Path", difficulty: "Medium", link: "https://leetcode.com/problems/simplify-path/" },
      { id: 24, title: "Binary Tree Vertical Order Traversal", difficulty: "Medium", link: "https://leetcode.com/problems/binary-tree-vertical-order-traversal/" },
      { id: 25, title: "Random Pick with Weight", difficulty: "Medium", link: "https://leetcode.com/problems/random-pick-with-weight/" },
      { id: 26, title: "Lowest Common Ancestor of a Binary Tree", difficulty: "Medium", link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/" },
      { id: 27, title: "Range Sum of BST", difficulty: "Easy", link: "https://leetcode.com/problems/range-sum-of-bst/" },
      { id: 28, title: "Dot Product of Two Sparse Vectors", difficulty: "Medium", link: "https://leetcode.com/problems/dot-product-of-two-sparse-vectors/" },
      { id: 29, title: "Nested List Weight Sum", difficulty: "Medium", link: "https://leetcode.com/problems/nested-list-weight-sum/" },
      { id: 30, title: "Basic Calculator II", difficulty: "Medium", link: "https://leetcode.com/problems/basic-calculator-ii/" },
      { id: 31, title: "Expression Add Operators", difficulty: "Hard", link: "https://leetcode.com/problems/expression-add-operators/" },
      { id: 32, title: "Word Break", difficulty: "Medium", link: "https://leetcode.com/problems/word-break/" },
      { id: 33, title: "Copy List with Random Pointer", difficulty: "Medium", link: "https://leetcode.com/problems/copy-list-with-random-pointer/" },
      { id: 34, title: "Exclusive Time of Functions", difficulty: "Medium", link: "https://leetcode.com/problems/exclusive-time-of-functions/" },
      { id: 35, title: "Diameter of Binary Tree", difficulty: "Easy", link: "https://leetcode.com/problems/diameter-of-binary-tree/" },
      { id: 36, title: "Subarray Sum Equals K", difficulty: "Medium", link: "https://leetcode.com/problems/subarray-sum-equals-k/" },
      { id: 37, title: "Convert Binary Search Tree to Sorted Doubly Linked List", difficulty: "Medium", link: "https://leetcode.com/problems/convert-binary-search-tree-to-sorted-doubly-linked-list/" },
      { id: 38, title: "Continuous Subarray Sum", difficulty: "Medium", link: "https://leetcode.com/problems/continuous-subarray-sum/" },
      { id: 39, title: "Valid Palindrome", difficulty: "Easy", link: "https://leetcode.com/problems/valid-palindrome/" },
      { id: 40, title: "Moving Average from Data Stream", difficulty: "Easy", link: "https://leetcode.com/problems/moving-average-from-data-stream/" },
      { id: 41, title: "Read N Characters Given Read4 II - Call multiple times", difficulty: "Hard", link: "https://leetcode.com/problems/read-n-characters-given-read4-ii-call-multiple-times/" },
      { id: 42, title: "Accounts Merge", difficulty: "Medium", link: "https://leetcode.com/problems/accounts-merge/" },
      { id: 43, title: "K Closest Points to Origin", difficulty: "Medium", link: "https://leetcode.com/problems/k-closest-points-to-origin/" },
      { id: 44, title: "Strobogrammatic Number", difficulty: "Easy", link: "https://leetcode.com/problems/strobogrammatic-number/" },
      { id: 45, title: "Strobogrammatic Number II", difficulty: "Medium", link: "https://leetcode.com/problems/strobogrammatic-number-ii/" }
    ]
  },
  {
    id: "microsoft",
    name: "Microsoft",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
    description: "Standard algorithms, Trees, Linked Lists, and Matrix manipulation.",
    questions: [
      { id: 1, title: "Spiral Matrix", difficulty: "Medium", link: "https://leetcode.com/problems/spiral-matrix/" },
      { id: 2, title: "Rotate List", difficulty: "Medium", link: "https://leetcode.com/problems/rotate-list/" },
      { id: 3, title: "Unique Paths", difficulty: "Medium", link: "https://leetcode.com/problems/unique-paths/" },
      { id: 4, title: "Set Matrix Zeroes", difficulty: "Medium", link: "https://leetcode.com/problems/set-matrix-zeroes/" },
      { id: 5, title: "Search a 2D Matrix", difficulty: "Medium", link: "https://leetcode.com/problems/search-a-2d-matrix/" },
      { id: 6, title: "Sort Colors", difficulty: "Medium", link: "https://leetcode.com/problems/sort-colors/" },
      { id: 7, title: "Word Search", difficulty: "Medium", link: "https://leetcode.com/problems/word-search/" },
      { id: 8, title: "Reverse Linked List II", difficulty: "Medium", link: "https://leetcode.com/problems/reverse-linked-list-ii/" },
      { id: 9, title: "Decode Ways", difficulty: "Medium", link: "https://leetcode.com/problems/decode-ways/" },
      { id: 10, title: "Validate Binary Search Tree", difficulty: "Medium", link: "https://leetcode.com/problems/validate-binary-search-tree/" },
      { id: 11, title: "Count Good Nodes in Binary Tree", difficulty: "Medium", link: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/" },
      { id: 12, title: "Minimum Deletions to Make Character Frequencies Unique", difficulty: "Medium", link: "https://leetcode.com/problems/minimum-deletions-to-make-character-frequencies-unique/" },
      { id: 13, title: "Sign of the Product of an Array", difficulty: "Easy", link: "https://leetcode.com/problems/sign-of-the-product-of-an-array/" },
      { id: 14, title: "Find N Unique Integers Sum up to Zero", difficulty: "Easy", link: "https://leetcode.com/problems/find-n-unique-integers-sum-up-to-zero/" },
      { id: 15, title: "Maximal Network Rank", difficulty: "Medium", link: "https://leetcode.com/problems/maximal-network-rank/" },
      { id: 16, title: "Count Substrings with Only One Distinct Letter", difficulty: "Easy", link: "https://leetcode.com/problems/count-substrings-with-only-one-distinct-letter/" },
      { id: 17, title: "Minimum Swaps to Group All 1's Together", difficulty: "Medium", link: "https://leetcode.com/problems/minimum-swaps-to-group-all-1s-together/" },
      { id: 18, title: "Design Tic-Tac-Toe", difficulty: "Medium", link: "https://leetcode.com/problems/design-tic-tac-toe/" },
      { id: 19, title: "Reverse Words in a String", difficulty: "Medium", link: "https://leetcode.com/problems/reverse-words-in-a-string/" },
      { id: 20, title: "Reverse Words in a String II", difficulty: "Medium", link: "https://leetcode.com/problems/reverse-words-in-a-string-ii/" },
      { id: 21, title: "Rotate Image", difficulty: "Medium", link: "https://leetcode.com/problems/rotate-image/" },
      { id: 22, title: "Group Anagrams", difficulty: "Medium", link: "https://leetcode.com/problems/group-anagrams/" },
      { id: 23, title: "Lowest Common Ancestor of a Binary Tree", difficulty: "Medium", link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/" },
      { id: 24, title: "Binary Tree Level Order Traversal", difficulty: "Medium", link: "https://leetcode.com/problems/binary-tree-level-order-traversal/" },
      { id: 25, title: "Binary Tree Zigzag Level Order Traversal", difficulty: "Medium", link: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/" },
      { id: 26, title: "Serialize and Deserialize Binary Tree", difficulty: "Hard", link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/" },
      { id: 27, title: "Populating Next Right Pointers in Each Node", difficulty: "Medium", link: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/" },
      { id: 28, title: "Populating Next Right Pointers in Each Node II", difficulty: "Medium", link: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii/" },
      { id: 29, title: "Copy List with Random Pointer", difficulty: "Medium", link: "https://leetcode.com/problems/copy-list-with-random-pointer/" },
      { id: 30, title: "Add Two Numbers", difficulty: "Medium", link: "https://leetcode.com/problems/add-two-numbers/" },
      { id: 31, title: "Add Two Numbers II", difficulty: "Medium", link: "https://leetcode.com/problems/add-two-numbers-ii/" },
      { id: 32, title: "Intersection of Two Linked Lists", difficulty: "Easy", link: "https://leetcode.com/problems/intersection-of-two-linked-lists/" },
      { id: 33, title: "Merge k Sorted Lists", difficulty: "Hard", link: "https://leetcode.com/problems/merge-k-sorted-lists/" },
      { id: 34, title: "Median of Two Sorted Arrays", difficulty: "Hard", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
      { id: 35, title: "Longest Palindromic Substring", difficulty: "Medium", link: "https://leetcode.com/problems/longest-palindromic-substring/" },
      { id: 36, title: "String to Integer (atoi)", difficulty: "Medium", link: "https://leetcode.com/problems/string-to-integer-atoi/" },
      { id: 37, title: "Wildcard Matching", difficulty: "Hard", link: "https://leetcode.com/problems/wildcard-matching/" },
      { id: 38, title: "Regular Expression Matching", difficulty: "Hard", link: "https://leetcode.com/problems/regular-expression-matching/" },
      { id: 39, title: "Trapping Rain Water", difficulty: "Hard", link: "https://leetcode.com/problems/trapping-rain-water/" },
      { id: 40, title: "Skyline Problem", difficulty: "Hard", link: "https://leetcode.com/problems/the-skyline-problem/" }
    ]
  },
  {
    id: "netflix",
    name: "Netflix",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg",
    description: "System Design heavy, but asks tricky Logical puzzles and Caching problems.",
    questions: [
      { id: 1, title: "LRU Cache", difficulty: "Medium", link: "https://leetcode.com/problems/lru-cache/" },
      { id: 2, title: "LFU Cache", difficulty: "Hard", link: "https://leetcode.com/problems/lfu-cache/" },
      { id: 3, title: "Merge k Sorted Lists", difficulty: "Hard", link: "https://leetcode.com/problems/merge-k-sorted-lists/" },
      { id: 4, title: "Serialize and Deserialize Binary Tree", difficulty: "Hard", link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/" },
      { id: 5, title: "Sliding Window Maximum", difficulty: "Hard", link: "https://leetcode.com/problems/sliding-window-maximum/" },
      { id: 6, title: "Group Anagrams", difficulty: "Medium", link: "https://leetcode.com/problems/group-anagrams/" },
      { id: 7, title: "Word Break", difficulty: "Medium", link: "https://leetcode.com/problems/word-break/" },
      { id: 8, title: "Word Break II", difficulty: "Hard", link: "https://leetcode.com/problems/word-break-ii/" },
      { id: 9, title: "First Missing Positive", difficulty: "Hard", link: "https://leetcode.com/problems/first-missing-positive/" },
      { id: 10, title: "Median of Two Sorted Arrays", difficulty: "Hard", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
      { id: 11, title: "Design Twitter", difficulty: "Medium", link: "https://leetcode.com/problems/design-twitter/" },
      { id: 12, title: "Meeting Rooms II", difficulty: "Medium", link: "https://leetcode.com/problems/meeting-rooms-ii/" },
      { id: 13, title: "Text Justification", difficulty: "Hard", link: "https://leetcode.com/problems/text-justification/" },
      { id: 14, title: "Trapping Rain Water", difficulty: "Hard", link: "https://leetcode.com/problems/trapping-rain-water/" },
      { id: 15, title: "Maximal Rectangle", difficulty: "Hard", link: "https://leetcode.com/problems/maximal-rectangle/" },
      { id: 16, title: "Best Time to Buy and Sell Stock", difficulty: "Easy", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/" },
      { id: 17, title: "Best Time to Buy and Sell Stock II", difficulty: "Medium", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/" },
      { id: 18, title: "Best Time to Buy and Sell Stock III", difficulty: "Hard", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/" },
      { id: 19, title: "Best Time to Buy and Sell Stock IV", difficulty: "Hard", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/" },
      { id: 20, title: "Letter Combinations of a Phone Number", difficulty: "Medium", link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/" },
      { id: 21, title: "Generate Parentheses", difficulty: "Medium", link: "https://leetcode.com/problems/generate-parentheses/" },
      { id: 22, title: "Merge Intervals", difficulty: "Medium", link: "https://leetcode.com/problems/merge-intervals/" },
      { id: 23, title: "Search in Rotated Sorted Array", difficulty: "Medium", link: "https://leetcode.com/problems/search-in-rotated-sorted-array/" },
      { id: 24, title: "Combination Sum", difficulty: "Medium", link: "https://leetcode.com/problems/combination-sum/" },
      { id: 25, title: "Permutations", difficulty: "Medium", link: "https://leetcode.com/problems/permutations/" }
    ]
  },
  {
    id: "uber",
    name: "Uber",
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/cc/Uber_logo_2018.png",
    description: "Graphs, Maps, and Scalability problems.",
    questions: [
      { id: 1, title: "Bus Routes", difficulty: "Hard", link: "https://leetcode.com/problems/bus-routes/" },
      { id: 2, title: "Course Schedule", difficulty: "Medium", link: "https://leetcode.com/problems/course-schedule/" },
      { id: 3, title: "Course Schedule II", difficulty: "Medium", link: "https://leetcode.com/problems/course-schedule-ii/" },
      { id: 4, title: "Alien Dictionary", difficulty: "Hard", link: "https://leetcode.com/problems/alien-dictionary/" },
      { id: 5, title: "Reconstruct Itinerary", difficulty: "Hard", link: "https://leetcode.com/problems/reconstruct-itinerary/" },
      { id: 6, title: "Word Ladder", difficulty: "Hard", link: "https://leetcode.com/problems/word-ladder/" },
      { id: 7, title: "Sudoku Solver", difficulty: "Hard", link: "https://leetcode.com/problems/sudoku-solver/" },
      { id: 8, title: "Text Justification", difficulty: "Hard", link: "https://leetcode.com/problems/text-justification/" },
      { id: 9, title: "Design Search Autocomplete System", difficulty: "Hard", link: "https://leetcode.com/problems/design-search-autocomplete-system/" },
      { id: 10, title: "Design Excel Sum Formula", difficulty: "Hard", link: "https://leetcode.com/problems/design-excel-sum-formula/" },
      { id: 11, title: "Design Hit Counter", difficulty: "Medium", link: "https://leetcode.com/problems/design-hit-counter/" },
      { id: 12, title: "Design Snake Game", difficulty: "Medium", link: "https://leetcode.com/problems/design-snake-game/" },
      { id: 13, title: "Design Phone Directory", difficulty: "Medium", link: "https://leetcode.com/problems/design-phone-directory/" },
      { id: 14, title: "Logger Rate Limiter", difficulty: "Easy", link: "https://leetcode.com/problems/logger-rate-limiter/" },
      { id: 15, title: "Top K Frequent Elements", difficulty: "Medium", link: "https://leetcode.com/problems/top-k-frequent-elements/" },
      { id: 16, title: "Construct Quad Tree", difficulty: "Medium", link: "https://leetcode.com/problems/construct-quad-tree/" },
      { id: 17, title: "Random Pick with Weight", difficulty: "Medium", link: "https://leetcode.com/problems/random-pick-with-weight/" },
      { id: 18, title: "Mine Sweeper", difficulty: "Medium", link: "https://leetcode.com/problems/minesweeper/" },
      { id: 19, title: "Number of Islands", difficulty: "Medium", link: "https://leetcode.com/problems/number-of-islands/" },
      { id: 20, title: "Surrounded Regions", difficulty: "Medium", link: "https://leetcode.com/problems/surrounded-regions/" },
      { id: 21, title: "Walls and Gates", difficulty: "Medium", link: "https://leetcode.com/problems/walls-and-gates/" },
      { id: 22, title: "Shortest Path in a Grid with Obstacles Elimination", difficulty: "Hard", link: "https://leetcode.com/problems/shortest-path-in-a-grid-with-obstacles-elimination/" },
      { id: 23, title: "Find the City With the Smallest Number of Neighbors at a Threshold Distance", difficulty: "Medium", link: "https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/" },
      { id: 24, title: "Path With Minimum Effort", difficulty: "Medium", link: "https://leetcode.com/problems/path-with-minimum-effort/" },
      { id: 25, title: "Cheapest Flights Within K Stops", difficulty: "Medium", link: "https://leetcode.com/problems/cheapest-flights-within-k-stops/" }
    ]
  },
  {
    id: "apple",
    name: "Apple",
    logo: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg",
    description: "Practical problems, Arrays, Strings, and C++ fundamentals.",
    questions: [
      { id: 1, title: "Two Sum", difficulty: "Easy", link: "https://leetcode.com/problems/two-sum/" },
      { id: 2, title: "3Sum", difficulty: "Medium", link: "https://leetcode.com/problems/3sum/" },
      { id: 3, title: "Merge Intervals", difficulty: "Medium", link: "https://leetcode.com/problems/merge-intervals/" },
      { id: 4, title: "Group Anagrams", difficulty: "Medium", link: "https://leetcode.com/problems/group-anagrams/" },
      { id: 5, title: "Valid Parentheses", difficulty: "Easy", link: "https://leetcode.com/problems/valid-parentheses/" },
      { id: 6, title: "Product of Array Except Self", difficulty: "Medium", link: "https://leetcode.com/problems/product-of-array-except-self/" },
      { id: 7, title: "Maximum Subarray", difficulty: "Medium", link: "https://leetcode.com/problems/maximum-subarray/" },
      { id: 8, title: "Climbing Stairs", difficulty: "Easy", link: "https://leetcode.com/problems/climbing-stairs/" },
      { id: 9, title: "Best Time to Buy and Sell Stock", difficulty: "Easy", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/" },
      { id: 10, title: "Longest Common Prefix", difficulty: "Easy", link: "https://leetcode.com/problems/longest-common-prefix/" },
      { id: 11, title: "Roman to Integer", difficulty: "Easy", link: "https://leetcode.com/problems/roman-to-integer/" },
      { id: 12, title: "Integer to Roman", difficulty: "Medium", link: "https://leetcode.com/problems/integer-to-roman/" },
      { id: 13, title: "Reverse Integer", difficulty: "Medium", link: "https://leetcode.com/problems/reverse-integer/" },
      { id: 14, title: "Palindrome Number", difficulty: "Easy", link: "https://leetcode.com/problems/palindrome-number/" },
      { id: 15, title: "Valid Anagram", difficulty: "Easy", link: "https://leetcode.com/problems/valid-anagram/" },
      { id: 16, title: "Fizz Buzz", difficulty: "Easy", link: "https://leetcode.com/problems/fizz-buzz/" },
      { id: 17, title: "Reverse String", difficulty: "Easy", link: "https://leetcode.com/problems/reverse-string/" },
      { id: 18, title: "Reverse Linked List", difficulty: "Easy", link: "https://leetcode.com/problems/reverse-linked-list/" },
      { id: 19, title: "Merge Two Sorted Lists", difficulty: "Easy", link: "https://leetcode.com/problems/merge-two-sorted-lists/" },
      { id: 20, title: "Maximum Depth of Binary Tree", difficulty: "Easy", link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/" },
      { id: 21, title: "Happy Number", difficulty: "Easy", link: "https://leetcode.com/problems/happy-number/" },
      { id: 22, title: "Plus One", difficulty: "Easy", link: "https://leetcode.com/problems/plus-one/" },
      { id: 23, title: "Sqrt(x)", difficulty: "Easy", link: "https://leetcode.com/problems/sqrtx/" },
      { id: 24, title: "Pow(x, n)", difficulty: "Medium", link: "https://leetcode.com/problems/powx-n/" },
      { id: 25, title: "Permutations", difficulty: "Medium", link: "https://leetcode.com/problems/permutations/" }
    ]
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/ca/LinkedIn_logo_initials.png",
    description: "HashMaps, Intervals, and 'Retain Best Cache' problems.",
    questions: [
      { id: 1, title: "Max Points on a Line", difficulty: "Hard", link: "https://leetcode.com/problems/max-points-on-a-line/" },
      { id: 2, title: "Shortest Word Distance", difficulty: "Easy", link: "https://leetcode.com/problems/shortest-word-distance/" },
      { id: 3, title: "Shortest Word Distance II", difficulty: "Medium", link: "https://leetcode.com/problems/shortest-word-distance-ii/" },
      { id: 4, title: "Find the Celebrity", difficulty: "Medium", link: "https://leetcode.com/problems/find-the-celebrity/" },
      { id: 5, title: "Paint House", difficulty: "Medium", link: "https://leetcode.com/problems/paint-house/" },
      { id: 6, title: "Paint House II", difficulty: "Hard", link: "https://leetcode.com/problems/paint-house-ii/" },
      { id: 7, title: "Nested List Weight Sum", difficulty: "Medium", link: "https://leetcode.com/problems/nested-list-weight-sum/" },
      { id: 8, title: "Factor Combinations", difficulty: "Medium", link: "https://leetcode.com/problems/factor-combinations/" },
      { id: 9, title: "Binary Tree Upside Down", difficulty: "Medium", link: "https://leetcode.com/problems/binary-tree-upside-down/" },
      { id: 10, title: "Can Place Flowers", difficulty: "Easy", link: "https://leetcode.com/problems/can-place-flowers/" },
      { id: 11, title: "Maximum Subarray", difficulty: "Medium", link: "https://leetcode.com/problems/maximum-subarray/" },
      { id: 12, title: "Product of Array Except Self", difficulty: "Medium", link: "https://leetcode.com/problems/product-of-array-except-self/" },
      { id: 13, title: "Merge Intervals", difficulty: "Medium", link: "https://leetcode.com/problems/merge-intervals/" },
      { id: 14, title: "Insert Interval", difficulty: "Medium", link: "https://leetcode.com/problems/insert-interval/" },
      { id: 15, title: "Pow(x, n)", difficulty: "Medium", link: "https://leetcode.com/problems/powx-n/" },
      { id: 16, title: "Lowest Common Ancestor of a Binary Tree", difficulty: "Medium", link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/" },
      { id: 17, title: "Symmetric Tree", difficulty: "Easy", link: "https://leetcode.com/problems/symmetric-tree/" },
      { id: 18, title: "Binary Tree Level Order Traversal", difficulty: "Medium", link: "https://leetcode.com/problems/binary-tree-level-order-traversal/" },
      { id: 19, title: "Second Minimum Node In a Binary Tree", difficulty: "Easy", link: "https://leetcode.com/problems/second-minimum-node-in-a-binary-tree/" },
      { id: 20, title: "Partition to K Equal Sum Subsets", difficulty: "Medium", link: "https://leetcode.com/problems/partition-to-k-equal-sum-subsets/" }
    ]
  },
  {
    id: "adobe",
    name: "Adobe",
    logo: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Adobe_Corporate_Logo.png",
    description: "Strings, Geometry, and DP.",
    questions: [
      { id: 1, title: "Two Sum", difficulty: "Easy", link: "https://leetcode.com/problems/two-sum/" },
      { id: 2, title: "Median of Two Sorted Arrays", difficulty: "Hard", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
      { id: 3, title: "Missing Number", difficulty: "Easy", link: "https://leetcode.com/problems/missing-number/" },
      { id: 4, title: "Reverse Integer", difficulty: "Medium", link: "https://leetcode.com/problems/reverse-integer/" },
      { id: 5, title: "Palindrome Number", difficulty: "Easy", link: "https://leetcode.com/problems/palindrome-number/" },
      { id: 6, title: "Container With Most Water", difficulty: "Medium", link: "https://leetcode.com/problems/container-with-most-water/" },
      { id: 7, title: "Integer to Roman", difficulty: "Medium", link: "https://leetcode.com/problems/integer-to-roman/" },
      { id: 8, title: "Longest Common Prefix", difficulty: "Easy", link: "https://leetcode.com/problems/longest-common-prefix/" },
      { id: 9, title: "3Sum", difficulty: "Medium", link: "https://leetcode.com/problems/3sum/" },
      { id: 10, title: "Multiply Strings", difficulty: "Medium", link: "https://leetcode.com/problems/multiply-strings/" },
      { id: 11, title: "String to Integer (atoi)", difficulty: "Medium", link: "https://leetcode.com/problems/string-to-integer-atoi/" },
      { id: 12, title: "Valid Parentheses", difficulty: "Easy", link: "https://leetcode.com/problems/valid-parentheses/" },
      { id: 13, title: "Merge Two Sorted Lists", difficulty: "Easy", link: "https://leetcode.com/problems/merge-two-sorted-lists/" },
      { id: 14, title: "Swap Nodes in Pairs", difficulty: "Medium", link: "https://leetcode.com/problems/swap-nodes-in-pairs/" },
      { id: 15, title: "Remove Duplicates from Sorted Array", difficulty: "Easy", link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/" },
      { id: 16, title: "Implement strStr()", difficulty: "Easy", link: "https://leetcode.com/problems/implement-strstr/" },
      { id: 17, title: "Length of Last Word", difficulty: "Easy", link: "https://leetcode.com/problems/length-of-last-word/" },
      { id: 18, title: "Plus One", difficulty: "Easy", link: "https://leetcode.com/problems/plus-one/" },
      { id: 19, title: "Add Binary", difficulty: "Easy", link: "https://leetcode.com/problems/add-binary/" },
      { id: 20, title: "Climbing Stairs", difficulty: "Easy", link: "https://leetcode.com/problems/climbing-stairs/" }
    ]
  },
  {
    id: "oracle",
    name: "Oracle",
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/50/Oracle_logo.svg",
    description: "Database internals, Strings, and Arrays.",
    questions: [
      { id: 1, title: "LRU Cache", difficulty: "Medium", link: "https://leetcode.com/problems/lru-cache/" },
      { id: 2, title: "Valid Parentheses", difficulty: "Easy", link: "https://leetcode.com/problems/valid-parentheses/" },
      { id: 3, title: "Merge Two Sorted Lists", difficulty: "Easy", link: "https://leetcode.com/problems/merge-two-sorted-lists/" },
      { id: 4, title: "Merge k Sorted Lists", difficulty: "Hard", link: "https://leetcode.com/problems/merge-k-sorted-lists/" },
      { id: 5, title: "Design Tic-Tac-Toe", difficulty: "Medium", link: "https://leetcode.com/problems/design-tic-tac-toe/" },
      { id: 6, title: "Word Search", difficulty: "Medium", link: "https://leetcode.com/problems/word-search/" },
      { id: 7, title: "Meeting Rooms II", difficulty: "Medium", link: "https://leetcode.com/problems/meeting-rooms-ii/" },
      { id: 8, title: "Product of Array Except Self", difficulty: "Medium", link: "https://leetcode.com/problems/product-of-array-except-self/" },
      { id: 9, title: "Copy List with Random Pointer", difficulty: "Medium", link: "https://leetcode.com/problems/copy-list-with-random-pointer/" },
      { id: 10, title: "Add Two Numbers", difficulty: "Medium", link: "https://leetcode.com/problems/add-two-numbers/" },
      { id: 11, title: "Two Sum", difficulty: "Easy", link: "https://leetcode.com/problems/two-sum/" },
      { id: 12, title: "Longest Substring Without Repeating Characters", difficulty: "Medium", link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
      { id: 13, title: "Median of Two Sorted Arrays", difficulty: "Hard", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
      { id: 14, title: "Longest Palindromic Substring", difficulty: "Medium", link: "https://leetcode.com/problems/longest-palindromic-substring/" },
      { id: 15, title: "Regular Expression Matching", difficulty: "Hard", link: "https://leetcode.com/problems/regular-expression-matching/" },
      { id: 16, title: "Container With Most Water", difficulty: "Medium", link: "https://leetcode.com/problems/container-with-most-water/" },
      { id: 17, title: "3Sum", difficulty: "Medium", link: "https://leetcode.com/problems/3sum/" },
      { id: 18, title: "Letter Combinations of a Phone Number", difficulty: "Medium", link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/" },
      { id: 19, title: "Remove Nth Node From End of List", difficulty: "Medium", link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
      { id: 20, title: "Valid Parentheses", difficulty: "Easy", link: "https://leetcode.com/problems/valid-parentheses/" }
    ]
  },
  {
    id: "salesforce",
    name: "Salesforce",
    logo: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Salesforce.com_logo.svg",
    description: "Java-heavy concepts, OOD, and Arrays.",
    questions: [
      { id: 1, title: "Valid Parentheses", difficulty: "Easy", link: "https://leetcode.com/problems/valid-parentheses/" },
      { id: 2, title: "Merge Intervals", difficulty: "Medium", link: "https://leetcode.com/problems/merge-intervals/" },
      { id: 3, title: "Top K Frequent Elements", difficulty: "Medium", link: "https://leetcode.com/problems/top-k-frequent-elements/" },
      { id: 4, title: "Kth Largest Element in an Array", difficulty: "Medium", link: "https://leetcode.com/problems/kth-largest-element-in-an-array/" },
      { id: 5, title: "Symmetric Tree", difficulty: "Easy", link: "https://leetcode.com/problems/symmetric-tree/" },
      { id: 6, title: "Diameter of Binary Tree", difficulty: "Easy", link: "https://leetcode.com/problems/diameter-of-binary-tree/" },
      { id: 7, title: "Maximum Depth of Binary Tree", difficulty: "Easy", link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/" },
      { id: 8, title: "Implement Trie (Prefix Tree)", difficulty: "Medium", link: "https://leetcode.com/problems/implement-trie-prefix-tree/" },
      { id: 9, title: "Course Schedule", difficulty: "Medium", link: "https://leetcode.com/problems/course-schedule/" },
      { id: 10, title: "Number of Islands", difficulty: "Medium", link: "https://leetcode.com/problems/number-of-islands/" },
      { id: 11, title: "Two Sum", difficulty: "Easy", link: "https://leetcode.com/problems/two-sum/" },
      { id: 12, title: "Add Two Numbers", difficulty: "Medium", link: "https://leetcode.com/problems/add-two-numbers/" },
      { id: 13, title: "Longest Substring Without Repeating Characters", difficulty: "Medium", link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
      { id: 14, title: "Median of Two Sorted Arrays", difficulty: "Hard", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
      { id: 15, title: "Longest Palindromic Substring", difficulty: "Medium", link: "https://leetcode.com/problems/longest-palindromic-substring/" },
      { id: 16, title: "Container With Most Water", difficulty: "Medium", link: "https://leetcode.com/problems/container-with-most-water/" },
      { id: 17, title: "3Sum", difficulty: "Medium", link: "https://leetcode.com/problems/3sum/" },
      { id: 18, title: "Letter Combinations of a Phone Number", difficulty: "Medium", link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/" },
      { id: 19, title: "Remove Nth Node From End of List", difficulty: "Medium", link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
      { id: 20, title: "Merge Two Sorted Lists", difficulty: "Easy", link: "https://leetcode.com/problems/merge-two-sorted-lists/" }
    ]
  },
  {
    id: "atlassian",
    name: "Atlassian",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Atlassian_logo.svg",
    description: "Rate Limiters, Caching, and Voting Systems.",
    questions: [
      { id: 1, title: "Logger Rate Limiter", difficulty: "Easy", link: "https://leetcode.com/problems/logger-rate-limiter/" },
      { id: 2, title: "Design Hit Counter", difficulty: "Medium", link: "https://leetcode.com/problems/design-hit-counter/" },
      { id: 3, title: "Rank Teams by Votes", difficulty: "Medium", link: "https://leetcode.com/problems/rank-teams-by-votes/" },
      { id: 4, title: "Find the City With the Smallest Number of Neighbors at a Threshold Distance", difficulty: "Medium", link: "https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/" },
      { id: 5, title: "Analyze User Website Visit Pattern", difficulty: "Medium", link: "https://leetcode.com/problems/analyze-user-website-visit-pattern/" },
      { id: 6, title: "Design Snake Game", difficulty: "Medium", link: "https://leetcode.com/problems/design-snake-game/" },
      { id: 7, title: "Design File System", difficulty: "Medium", link: "https://leetcode.com/problems/design-file-system/" },
      { id: 8, title: "Meeting Rooms II", difficulty: "Medium", link: "https://leetcode.com/problems/meeting-rooms-ii/" },
      { id: 9, title: "Merge Intervals", difficulty: "Medium", link: "https://leetcode.com/problems/merge-intervals/" },
      { id: 10, title: "Single-Threaded CPU", difficulty: "Medium", link: "https://leetcode.com/problems/single-threaded-cpu/" },
      { id: 11, title: "Two Sum", difficulty: "Easy", link: "https://leetcode.com/problems/two-sum/" },
      { id: 12, title: "Add Two Numbers", difficulty: "Medium", link: "https://leetcode.com/problems/add-two-numbers/" },
      { id: 13, title: "Longest Substring Without Repeating Characters", difficulty: "Medium", link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
      { id: 14, title: "Median of Two Sorted Arrays", difficulty: "Hard", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
      { id: 15, title: "Longest Palindromic Substring", difficulty: "Medium", link: "https://leetcode.com/problems/longest-palindromic-substring/" },
      { id: 16, title: "Container With Most Water", difficulty: "Medium", link: "https://leetcode.com/problems/container-with-most-water/" },
      { id: 17, title: "3Sum", difficulty: "Medium", link: "https://leetcode.com/problems/3sum/" },
      { id: 18, title: "Letter Combinations of a Phone Number", difficulty: "Medium", link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/" },
      { id: 19, title: "Remove Nth Node From End of List", difficulty: "Medium", link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
      { id: 20, title: "Valid Parentheses", difficulty: "Easy", link: "https://leetcode.com/problems/valid-parentheses/" }
    ]
  },
  {
    id: "goldman-sachs",
    name: "Goldman Sachs",
    logo: "https://upload.wikimedia.org/wikipedia/commons/6/61/Goldman_Sachs.svg",
    description: "Math, DP, and Matrix problems.",
    questions: [
      { id: 1, title: "Trapping Rain Water", difficulty: "Hard", link: "https://leetcode.com/problems/trapping-rain-water/" },
      { id: 2, title: "Median of Two Sorted Arrays", difficulty: "Hard", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
      { id: 3, title: "String Compression", difficulty: "Medium", link: "https://leetcode.com/problems/string-compression/" },
      { id: 4, title: "High Five", difficulty: "Easy", link: "https://leetcode.com/problems/high-five/" },
      { id: 5, title: "Fraction to Recurring Decimal", difficulty: "Medium", link: "https://leetcode.com/problems/fraction-to-recurring-decimal/" },
      { id: 6, title: "Group Anagrams", difficulty: "Medium", link: "https://leetcode.com/problems/group-anagrams/" },
      { id: 7, title: "Best Time to Buy and Sell Stock", difficulty: "Easy", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/" },
      { id: 8, title: "Robot Bounded In Circle", difficulty: "Medium", link: "https://leetcode.com/problems/robot-bounded-in-circle/" },
      { id: 9, title: "Minimum Size Subarray Sum", difficulty: "Medium", link: "https://leetcode.com/problems/minimum-size-subarray-sum/" },
      { id: 10, title: "Knight Probability in Chessboard", difficulty: "Medium", link: "https://leetcode.com/problems/knight-probability-in-chessboard/" },
      { id: 11, title: "Two Sum", difficulty: "Easy", link: "https://leetcode.com/problems/two-sum/" },
      { id: 12, title: "Add Two Numbers", difficulty: "Medium", link: "https://leetcode.com/problems/add-two-numbers/" },
      { id: 13, title: "Longest Substring Without Repeating Characters", difficulty: "Medium", link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
      { id: 14, title: "Longest Palindromic Substring", difficulty: "Medium", link: "https://leetcode.com/problems/longest-palindromic-substring/" },
      { id: 15, title: "Container With Most Water", difficulty: "Medium", link: "https://leetcode.com/problems/container-with-most-water/" },
      { id: 16, title: "3Sum", difficulty: "Medium", link: "https://leetcode.com/problems/3sum/" },
      { id: 17, title: "Letter Combinations of a Phone Number", difficulty: "Medium", link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/" },
      { id: 18, title: "Remove Nth Node From End of List", difficulty: "Medium", link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
      { id: 19, title: "Valid Parentheses", difficulty: "Easy", link: "https://leetcode.com/problems/valid-parentheses/" },
      { id: 20, title: "Merge Two Sorted Lists", difficulty: "Easy", link: "https://leetcode.com/problems/merge-two-sorted-lists/" }
    ]
  },
  {
    id: "jpmorgan",
    name: "JPMorgan",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/af/J_P_Morgan_Chase_Logo_2008_1.svg",
    description: "Strings, Arrays, and simple Trees.",
    questions: [
      { id: 1, title: "Happy Number", difficulty: "Easy", link: "https://leetcode.com/problems/happy-number/" },
      { id: 2, title: "Fibonacci Number", difficulty: "Easy", link: "https://leetcode.com/problems/fibonacci-number/" },
      { id: 3, title: "Merge Sorted Array", difficulty: "Easy", link: "https://leetcode.com/problems/merge-sorted-array/" },
      { id: 4, title: "Valid Parentheses", difficulty: "Easy", link: "https://leetcode.com/problems/valid-parentheses/" },
      { id: 5, title: "Coin Change", difficulty: "Medium", link: "https://leetcode.com/problems/coin-change/" },
      { id: 6, title: "Letter Combinations of a Phone Number", difficulty: "Medium", link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/" },
      { id: 7, title: "Number of Islands", difficulty: "Medium", link: "https://leetcode.com/problems/number-of-islands/" },
      { id: 8, title: "Maximum Subarray", difficulty: "Medium", link: "https://leetcode.com/problems/maximum-subarray/" },
      { id: 9, title: "Decode Ways", difficulty: "Medium", link: "https://leetcode.com/problems/decode-ways/" },
      { id: 10, title: "Count and Say", difficulty: "Medium", link: "https://leetcode.com/problems/count-and-say/" },
      { id: 11, title: "Two Sum", difficulty: "Easy", link: "https://leetcode.com/problems/two-sum/" },
      { id: 12, title: "Add Two Numbers", difficulty: "Medium", link: "https://leetcode.com/problems/add-two-numbers/" },
      { id: 13, title: "Longest Substring Without Repeating Characters", difficulty: "Medium", link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
      { id: 14, title: "Longest Palindromic Substring", difficulty: "Medium", link: "https://leetcode.com/problems/longest-palindromic-substring/" },
      { id: 15, title: "Container With Most Water", difficulty: "Medium", link: "https://leetcode.com/problems/container-with-most-water/" },
      { id: 16, title: "3Sum", difficulty: "Medium", link: "https://leetcode.com/problems/3sum/" },
      { id: 17, title: "Remove Nth Node From End of List", difficulty: "Medium", link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
      { id: 18, title: "Merge Two Sorted Lists", difficulty: "Easy", link: "https://leetcode.com/problems/merge-two-sorted-lists/" },
      { id: 19, title: "Remove Duplicates from Sorted Array", difficulty: "Easy", link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/" },
      { id: 20, title: "Implement strStr()", difficulty: "Easy", link: "https://leetcode.com/problems/implement-strstr/" }
    ]
  },
  {
    id: "doordash",
    name: "DoorDash",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/DoorDash_Logo.svg",
    description: "Graphs (City map), Intervals, and Scheduling.",
    questions: [
      { id: 1, title: "Employee Free Time", difficulty: "Hard", link: "https://leetcode.com/problems/employee-free-time/" },
      { id: 2, title: "Meeting Rooms II", difficulty: "Medium", link: "https://leetcode.com/problems/meeting-rooms-ii/" },
      { id: 3, title: "Design In-Memory File System", difficulty: "Hard", link: "https://leetcode.com/problems/design-in-memory-file-system/" },
      { id: 4, title: "Sudoku Solver", difficulty: "Hard", link: "https://leetcode.com/problems/sudoku-solver/" },
      { id: 5, title: "Maximum Profit in Job Scheduling", difficulty: "Hard", link: "https://leetcode.com/problems/maximum-profit-in-job-scheduling/" },
      { id: 6, title: "Course Schedule II", difficulty: "Medium", link: "https://leetcode.com/problems/course-schedule-ii/" },
      { id: 7, title: "Basic Calculator", difficulty: "Hard", link: "https://leetcode.com/problems/basic-calculator/" },
      { id: 8, title: "Basic Calculator II", difficulty: "Medium", link: "https://leetcode.com/problems/basic-calculator-ii/" },
      { id: 9, title: "Basic Calculator III", difficulty: "Hard", link: "https://leetcode.com/problems/basic-calculator-iii/" },
      { id: 10, title: "Shortest Path to Get Food", difficulty: "Medium", link: "https://leetcode.com/problems/shortest-path-to-get-food/" },
      { id: 11, title: "Number of Islands", difficulty: "Medium", link: "https://leetcode.com/problems/number-of-islands/" },
      { id: 12, title: "Max Area of Island", difficulty: "Medium", link: "https://leetcode.com/problems/max-area-of-island/" },
      { id: 13, title: "Merge Intervals", difficulty: "Medium", link: "https://leetcode.com/problems/merge-intervals/" },
      { id: 14, title: "Insert Interval", difficulty: "Medium", link: "https://leetcode.com/problems/insert-interval/" },
      { id: 15, title: "Two Sum", difficulty: "Easy", link: "https://leetcode.com/problems/two-sum/" },
      { id: 16, title: "3Sum", difficulty: "Medium", link: "https://leetcode.com/problems/3sum/" },
      { id: 17, title: "Valid Parentheses", difficulty: "Easy", link: "https://leetcode.com/problems/valid-parentheses/" },
      { id: 18, title: "Merge Two Sorted Lists", difficulty: "Easy", link: "https://leetcode.com/problems/merge-two-sorted-lists/" },
      { id: 19, title: "LRU Cache", difficulty: "Medium", link: "https://leetcode.com/problems/lru-cache/" },
      { id: 20, title: "Design HashMap", difficulty: "Easy", link: "https://leetcode.com/problems/design-hashmap/" }
    ]
  },
  {
    id: "stripe",
    name: "Stripe",
    logo: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Stripe_Logo%2C_revised_2016.svg",
    description: "String manipulation, Parsing, and Database concepts.",
    questions: [
      { id: 1, title: "First Missing Positive", difficulty: "Hard", link: "https://leetcode.com/problems/first-missing-positive/" },
      { id: 2, title: "Text Justification", difficulty: "Hard", link: "https://leetcode.com/problems/text-justification/" },
      { id: 3, title: "Decode String", difficulty: "Medium", link: "https://leetcode.com/problems/decode-string/" },
      { id: 4, title: "Flatten Nested List Iterator", difficulty: "Medium", link: "https://leetcode.com/problems/flatten-nested-list-iterator/" },
      { id: 5, title: "Insert Delete GetRandom O(1)", difficulty: "Medium", link: "https://leetcode.com/problems/insert-delete-getrandom-o1/" },
      { id: 6, title: "Logger Rate Limiter", difficulty: "Easy", link: "https://leetcode.com/problems/logger-rate-limiter/" },
      { id: 7, title: "Design Tic-Tac-Toe", difficulty: "Medium", link: "https://leetcode.com/problems/design-tic-tac-toe/" },
      { id: 8, title: "Design Search Autocomplete System", difficulty: "Hard", link: "https://leetcode.com/problems/design-search-autocomplete-system/" },
      { id: 9, title: "Basic Calculator II", difficulty: "Medium", link: "https://leetcode.com/problems/basic-calculator-ii/" },
      { id: 10, title: "Remove Invalid Parentheses", difficulty: "Hard", link: "https://leetcode.com/problems/remove-invalid-parentheses/" },
      { id: 11, title: "Two Sum", difficulty: "Easy", link: "https://leetcode.com/problems/two-sum/" },
      { id: 12, title: "3Sum", difficulty: "Medium", link: "https://leetcode.com/problems/3sum/" },
      { id: 13, title: "Valid Parentheses", difficulty: "Easy", link: "https://leetcode.com/problems/valid-parentheses/" },
      { id: 14, title: "Merge Intervals", difficulty: "Medium", link: "https://leetcode.com/problems/merge-intervals/" },
      { id: 15, title: "LRU Cache", difficulty: "Medium", link: "https://leetcode.com/problems/lru-cache/" },
      { id: 16, title: "Meeting Rooms II", difficulty: "Medium", link: "https://leetcode.com/problems/meeting-rooms-ii/" },
      { id: 17, title: "Reorganize String", difficulty: "Medium", link: "https://leetcode.com/problems/reorganize-string/" },
      { id: 18, title: "Top K Frequent Elements", difficulty: "Medium", link: "https://leetcode.com/problems/top-k-frequent-elements/" },
      { id: 19, title: "Implement Trie (Prefix Tree)", difficulty: "Medium", link: "https://leetcode.com/problems/implement-trie-prefix-tree/" },
      { id: 20, title: "Word Search II", difficulty: "Hard", link: "https://leetcode.com/problems/word-search-ii/" }
    ]
  },
  {
    id: "snowflake",
    name: "Snowflake",
    logo: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Snowflake_Logo.svg",
    description: "Concurrency, Systems, and complex Arrays.",
    questions: [
      { id: 1, title: "Trapping Rain Water", difficulty: "Hard", link: "https://leetcode.com/problems/trapping-rain-water/" },
      { id: 2, title: "Trapping Rain Water II", difficulty: "Hard", link: "https://leetcode.com/problems/trapping-rain-water-ii/" },
      { id: 3, title: "Word Ladder II", difficulty: "Hard", link: "https://leetcode.com/problems/word-ladder-ii/" },
      { id: 4, title: "Palindrome Pairs", difficulty: "Hard", link: "https://leetcode.com/problems/palindrome-pairs/" },
      { id: 5, title: "Max Points on a Line", difficulty: "Hard", link: "https://leetcode.com/problems/max-points-on-a-line/" },
      { id: 6, title: "Concatenated Words", difficulty: "Hard", link: "https://leetcode.com/problems/concatenated-words/" },
      { id: 7, title: "Design File System", difficulty: "Medium", link: "https://leetcode.com/problems/design-file-system/" },
      { id: 8, title: "Design In-Memory File System", difficulty: "Hard", link: "https://leetcode.com/problems/design-in-memory-file-system/" },
      { id: 9, title: "Maximum Frequency Stack", difficulty: "Hard", link: "https://leetcode.com/problems/maximum-frequency-stack/" },
      { id: 10, title: "Parallel Courses III", difficulty: "Hard", link: "https://leetcode.com/problems/parallel-courses-iii/" },
      { id: 11, title: "Two Sum", difficulty: "Easy", link: "https://leetcode.com/problems/two-sum/" },
      { id: 12, title: "Longest Substring Without Repeating Characters", difficulty: "Medium", link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
      { id: 13, title: "Median of Two Sorted Arrays", difficulty: "Hard", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
      { id: 14, title: "Longest Palindromic Substring", difficulty: "Medium", link: "https://leetcode.com/problems/longest-palindromic-substring/" },
      { id: 15, title: "3Sum", difficulty: "Medium", link: "https://leetcode.com/problems/3sum/" },
      { id: 16, title: "Merge Intervals", difficulty: "Medium", link: "https://leetcode.com/problems/merge-intervals/" },
      { id: 17, title: "Group Anagrams", difficulty: "Medium", link: "https://leetcode.com/problems/group-anagrams/" },
      { id: 18, title: "Word Break", difficulty: "Medium", link: "https://leetcode.com/problems/word-break/" },
      { id: 19, title: "Word Break II", difficulty: "Hard", link: "https://leetcode.com/problems/word-break-ii/" },
      { id: 20, title: "LRU Cache", difficulty: "Medium", link: "https://leetcode.com/problems/lru-cache/" }
    ]
  },
  {
    id: "databricks",
    name: "Databricks",
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/93/Databricks_Logo.png",
    description: "Trees, Graphs, and Hard implementation problems.",
    questions: [
      { id: 1, title: "Closest Leaf in a Binary Tree", difficulty: "Medium", link: "https://leetcode.com/problems/closest-leaf-in-a-binary-tree/" },
      { id: 2, title: "Robot Room Cleaner", difficulty: "Hard", link: "https://leetcode.com/problems/robot-room-cleaner/" },
      { id: 3, title: "Design Excel Sum Formula", difficulty: "Hard", link: "https://leetcode.com/problems/design-excel-sum-formula/" },
      { id: 4, title: "Bold Words in String", difficulty: "Medium", link: "https://leetcode.com/problems/bold-words-in-string/" },
      { id: 5, title: "Add Bold Tag in String", difficulty: "Medium", link: "https://leetcode.com/problems/add-bold-tag-in-string/" },
      { id: 6, title: "Range Module", difficulty: "Hard", link: "https://leetcode.com/problems/range-module/" },
      { id: 7, title: "Basic Calculator III", difficulty: "Hard", link: "https://leetcode.com/problems/basic-calculator-iii/" },
      { id: 8, title: "Serialize and Deserialize N-ary Tree", difficulty: "Hard", link: "https://leetcode.com/problems/serialize-and-deserialize-n-ary-tree/" },
      { id: 9, title: "Web Crawler", difficulty: "Medium", link: "https://leetcode.com/problems/web-crawler/" },
      { id: 10, title: "Web Crawler Multithreaded", difficulty: "Medium", link: "https://leetcode.com/problems/web-crawler-multithreaded/" },
      { id: 11, title: "Two Sum", difficulty: "Easy", link: "https://leetcode.com/problems/two-sum/" },
      { id: 12, title: "Add Two Numbers", difficulty: "Medium", link: "https://leetcode.com/problems/add-two-numbers/" },
      { id: 13, title: "Longest Substring Without Repeating Characters", difficulty: "Medium", link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
      { id: 14, title: "Median of Two Sorted Arrays", difficulty: "Hard", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
      { id: 15, title: "Longest Palindromic Substring", difficulty: "Medium", link: "https://leetcode.com/problems/longest-palindromic-substring/" },
      { id: 16, title: "Regular Expression Matching", difficulty: "Hard", link: "https://leetcode.com/problems/regular-expression-matching/" },
      { id: 17, title: "Container With Most Water", difficulty: "Medium", link: "https://leetcode.com/problems/container-with-most-water/" },
      { id: 18, title: "3Sum", difficulty: "Medium", link: "https://leetcode.com/problems/3sum/" },
      { id: 19, title: "Letter Combinations of a Phone Number", difficulty: "Medium", link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/" },
      { id: 20, title: "Remove Nth Node From End of List", difficulty: "Medium", link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" }
    ]
  },
  {
    id: "bloomberg",
    name: "Bloomberg",
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/52/Bloomberg_logo.svg",
    description: "Stacks, Queues, and Linked List manipulation.",
    questions: [
      { id: 1, title: "Design Underground System", difficulty: "Medium", link: "https://leetcode.com/problems/design-underground-system/" },
      { id: 2, title: "Design Browser History", difficulty: "Medium", link: "https://leetcode.com/problems/design-browser-history/" },
      { id: 3, title: "Flatten a Multilevel Doubly Linked List", difficulty: "Medium", link: "https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/" },
      { id: 4, title: "Invalid Transactions", difficulty: "Medium", link: "https://leetcode.com/problems/invalid-transactions/" },
      { id: 5, title: "Candy Crush", difficulty: "Medium", link: "https://leetcode.com/problems/candy-crush/" },
      { id: 6, title: "Remove All Adjacent Duplicates in String II", difficulty: "Medium", link: "https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string-ii/" },
      { id: 7, title: "Decode String", difficulty: "Medium", link: "https://leetcode.com/problems/decode-string/" },
      { id: 8, title: "Two City Scheduling", difficulty: "Medium", link: "https://leetcode.com/problems/two-city-scheduling/" },
      { id: 9, title: "Meeting Rooms II", difficulty: "Medium", link: "https://leetcode.com/problems/meeting-rooms-ii/" },
      { id: 10, title: "Insert Delete GetRandom O(1)", difficulty: "Medium", link: "https://leetcode.com/problems/insert-delete-getrandom-o1/" },
      { id: 11, title: "LRU Cache", difficulty: "Medium", link: "https://leetcode.com/problems/lru-cache/" },
      { id: 12, title: "Merge Intervals", difficulty: "Medium", link: "https://leetcode.com/problems/merge-intervals/" },
      { id: 13, title: "Add Two Numbers", difficulty: "Medium", link: "https://leetcode.com/problems/add-two-numbers/" },
      { id: 14, title: "Trapping Rain Water", difficulty: "Hard", link: "https://leetcode.com/problems/trapping-rain-water/" },
      { id: 15, title: "Copy List with Random Pointer", difficulty: "Medium", link: "https://leetcode.com/problems/copy-list-with-random-pointer/" },
      { id: 16, title: "Valid Parentheses", difficulty: "Easy", link: "https://leetcode.com/problems/valid-parentheses/" },
      { id: 17, title: "Number of Islands", difficulty: "Medium", link: "https://leetcode.com/problems/number-of-islands/" },
      { id: 18, title: "Maximal Square", difficulty: "Medium", link: "https://leetcode.com/problems/maximal-square/" },
      { id: 19, title: "Sort Characters By Frequency", difficulty: "Medium", link: "https://leetcode.com/problems/sort-characters-by-frequency/" },
      { id: 20, title: "Top K Frequent Elements", difficulty: "Medium", link: "https://leetcode.com/problems/top-k-frequent-elements/" }
    ]
  },
  {
    id: "airbnb",
    name: "Airbnb",
    logo: "https://upload.wikimedia.org/wikipedia/commons/6/69/Airbnb_Logo_B%C3%A9lo.svg",
    description: "Graph traversals, Shortest path (Flight/Booking systems).",
    questions: [
      { id: 1, title: "Alien Dictionary", difficulty: "Hard", link: "https://leetcode.com/problems/alien-dictionary/" },
      { id: 2, title: "Palindrome Pairs", difficulty: "Hard", link: "https://leetcode.com/problems/palindrome-pairs/" },
      { id: 3, title: "Sliding Puzzle", difficulty: "Hard", link: "https://leetcode.com/problems/sliding-puzzle/" },
      { id: 4, title: "IP to CIDR", difficulty: "Easy", link: "https://leetcode.com/problems/ip-to-cidr/" },
      { id: 5, title: "Display Table of Food Orders in a Restaurant", difficulty: "Medium", link: "https://leetcode.com/problems/display-table-of-food-orders-in-a-restaurant/" },
      { id: 6, title: "Menu Redistribution", difficulty: "Medium", link: "https://leetcode.com/problems/menu-redistribution/" },
      { id: 7, title: "Cheapest Flights Within K Stops", difficulty: "Medium", link: "https://leetcode.com/problems/cheapest-flights-within-k-stops/" },
      { id: 8, title: "Text Justification", difficulty: "Hard", link: "https://leetcode.com/problems/text-justification/" },
      { id: 9, title: "Round Prices", difficulty: "Medium", link: "https://leetcode.com/problems/round-prices/" },
      { id: 10, title: "Pour Water", difficulty: "Medium", link: "https://leetcode.com/problems/pour-water/" },
      { id: 11, title: "Two Sum", difficulty: "Easy", link: "https://leetcode.com/problems/two-sum/" },
      { id: 12, title: "Add Two Numbers", difficulty: "Medium", link: "https://leetcode.com/problems/add-two-numbers/" },
      { id: 13, title: "Longest Substring Without Repeating Characters", difficulty: "Medium", link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
      { id: 14, title: "Median of Two Sorted Arrays", difficulty: "Hard", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
      { id: 15, title: "Longest Palindromic Substring", difficulty: "Medium", link: "https://leetcode.com/problems/longest-palindromic-substring/" },
      { id: 16, title: "Regular Expression Matching", difficulty: "Hard", link: "https://leetcode.com/problems/regular-expression-matching/" },
      { id: 17, title: "Container With Most Water", difficulty: "Medium", link: "https://leetcode.com/problems/container-with-most-water/" },
      { id: 18, title: "3Sum", difficulty: "Medium", link: "https://leetcode.com/problems/3sum/" },
      { id: 19, title: "Letter Combinations of a Phone Number", difficulty: "Medium", link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/" },
      { id: 20, title: "Remove Nth Node From End of List", difficulty: "Medium", link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" }
    ]
  }
];